"""
A module for defining the JSON parser's token structure.
"""

from dataclasses import dataclass
from enum import Enum, auto

class TokenType(Enum):
    """Enumeration of all valid JSON token types."""

    # Structural tokens generated by the lexer
    LBRACE = auto()   # {
    RBRACE = auto()   # }
    LBRACKET = auto() # [
    RBRACKET = auto() # ]
    COMMA = auto()    # ,
    COLON = auto()    # :

    # Value tokens generated by the lexer
    STRING = auto()   # "string"
    NUMBER = auto()   # 123.45
    TRUE = auto()     # true
    FALSE = auto()    # false
    NULL = auto()     # null

    # Special tokens generated by the lexer
    EOF = auto()      # End of input

    # Special tokens generated by the parser (not emitted by the lexer)
    KEY   = auto()    # A JSON object key (string)  ###JDG TODO: Remove if not needed.
    VALUE = auto()    # A generic value that is the result of a reduce operation.

@dataclass
class Token:
    """Represents a single token in the JSON source."""

    type: TokenType
    value: any = None
    line: int = 0

    def __str__(self):
        return f"{self.type.name}({self.value}) at line {self.line}"

    def is_value(self):
        """Helper method to determine if this token is a value token."""
        values = {TokenType.STRING, TokenType.NUMBER, TokenType.TRUE, TokenType.FALSE, TokenType.NULL, TokenType.VALUE}
        return self.type in values
